### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by al-wei** [Henrykado/Somnia-Refreshed#2]
*Before reporting a bug, please make sure you're using the newest version of Somnia*
Somnia-1.0.1
**Describe the bug**
I got into Nether and the game kept crashing and I couldn't get into the map.
https://mclo.gs/0hx8EEy
**Is this bug related to another mod?**

**To Reproduce**
Steps to reproduce the bug:
1.
2.
3.
4.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ACGaming** [comment]
Particle rendering error, particle in question is from Moar TCon.

Other mentioned mods are Alfheim and Particle Culling, so it might be unrelated to Somnia.

**Comment by al-wei** [comment]
I'll test it.
